### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [NVIDIA/NVTabular#1042]
The error below was fixed but we are still getting the this error for rename op;

Failed to transform operator <nvtabular.ops.rename.Rename object at 0x7f5490c50fd0>
Traceback (most recent call last):
  File "/model/ronay/models/model_nvt/1/model.py", line 292, in _transform_tensors
    tensors = workflow_node.op.transform(
  File "/model/recent-nvt/NVTabular/nvtabular/ops/rename.py", line 52, in transform
    df.columns = self.output_column_names(col_selector)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 664, in __setattr__
    super().__setattr__(key, col)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 2707, in columns
    raise ValueError(
ValueError: Length mismatch: expected 17 elements ,got 1 elements
0818 01:14:50.587463 147 pb_stub.cc:555] ValueError: Length mismatch: expected 17 elements ,got 1 elements

At:
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(2707): columns
  /usr/lib/python3.8/contextlib.py(75): inner
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(677): __setattr__
  /model/recent-nvt/NVTabular/nvtabular/ops/rename.py(52): transform
  /model/ronay/models/model_nvt/1/model.py(299): _transform_tensors
  /model/ronay/models/model_nvt/1/model.py(264): _transform_tensors
  /model/ronay/models/model_nvt/1/model.py(264): _transform_tensors
  /model/ronay/models/model_nvt/1/model.py(264): _transform_tensors
  /model/ronay/models/model_nvt/1/model.py(144): execute

I0818 01:14:50.588710 137 python.cc:373] Failed to process the batch of requests.

**Comment by rnyak** [comment]
@oyilmaz-nvidia In addition to that the error I also get on the triton container terminal:


```
Failed to transform operator <nvtabular.ops.rename.Rename object at 0x7f53fe652070>
Traceback (most recent call last):
  File "/root/model_nvt/1/model.py", line 292, in _transform_tensors
    tensors = workflow_node.op.transform(
  File "/root/.local/lib/python3.8/site-packages/nvtabular-0.6.0+14.g5ece720-py3.8-linux-x86_64.egg/nvtabular/ops/rename.py", line 52, in transform
    df.columns = self.output_column_names(col_selector)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 664, in __setattr__
    super().__setattr__(key, col)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 2707, in columns
    raise ValueError(
ValueError: Length mismatch: expected 3 elements ,got 1 elements
0818 13:13:55.064044 1303 pb_stub.cc:555] ValueError: Length mismatch: expected 3 elements ,got 1 elements
```

Looks like the issue is that `model.py` does not remove columns from the output, when our NVTabular workflow uses the `-` operator.

@bschifferer  for viz.

**Comment by karlhigley** [comment]
At least for the `Rename` op, it looks like the issue is that it's returning a `ColumnSelector` object instead of a list of string column names. The fix is just to call `.names` on the return value of `self.output_column_names` to get the list of column names. Surprised that wasn't caught by the test suite, but I'll put in a PR to fix that.
