### ISSUE TITLE
[BUG] NVT ETL results in error when served to Triton IS

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#1075]
**Describe the bug**

I am getting the following error when my NVT pipeline, `model_nvt`, is served to TIS:

```
I0827 19:35:11.159577 1094 python.cc:455] model model_nvt, instance model_nvt, executing 1 requests
Failed to transform operator <__main__.ItemRecency object at 0x7f0bebb40640>
Traceback (most recent call last):
  File "/root/models/model_nvt/1/model.py", line 293, in _transform_tensors
    tensors = workflow_node.op.transform(
  File "/tmp/ipykernel_10278/3259623611.py", line 7, in transform
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 723, in __getitem__
    return self._get_columns_by_label(arg, downcast=True)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 1449, in _get_columns_by_label
    new_data = super()._get_columns_by_label(labels, downcast)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/frame.py", line 630, in _get_columns_by_label
    return self._data.select_by_label(labels)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py", line 346, in select_by_label
    return self._select_by_label_grouped(key)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py", line 408, in _select_by_label_grouped
    result = self._grouped_data[key]
KeyError: 'prod_first_event_time_ts'
0827 19:35:12.064597 1130 pb_stub.cc:555] KeyError: 'prod_first_event_time_ts'

At:
  /usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py(408): _select_by_label_grouped
  /usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py(346): select_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/frame.py(630): _get_columns_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(1449): _get_columns_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(723): __getitem__
  /usr/lib/python3.8/contextlib.py(75): inner
  /tmp/ipykernel_10278/3259623611.py(7): transform
  /root/models/model_nvt/1/model.py(300): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(143): execute

I0827 19:35:12.064981 1094 python.cc:373] Failed to process the batch of requests.
I0827 19:35:12.065029 1094 grpc_server.cc:3304] ModelInferHandler::InferResponseComplete, 1 step ISSUED
I0827 19:35:12.065238 1094 grpc_server.cc:2873] ModelInferHandler::InferRequestComplete
I0827 19:35:12.065253 1094 grpc_server.cc:3151] Process for ModelInferHandler, rpc_ok=1, 1 step COMPLETE
I0827 19:35:12.065285 1094 grpc_server.cc:2195] Done for ModelInferHandler, 1
```

**Steps/Code to reproduce bug**

- Please find the ETL pipeline code in this gist:

https://gist.github.com/rnyak/e9b6d9d96718181aff1c9d47dca6aefc

- the client request code is here:

https://gist.github.com/rnyak/d58b40eff9c3c7f37d6a80280af03a94

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]  Docker: `merlin-pytorch-training` and `merlin-inference` with the latest main branch.
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 

**Additional context**

If I remove the `ItemRecency` custom op, then I get error about `price` column:

```
Failed to transform operator <nvtabular.ops.lambdaop.LambdaOp object at 0x7f26c247d850>
Traceback (most recent call last):
  File "/root/models/model_nvt/1/model.py", line 293, in _transform_tensors
    tensors = workflow_node.op.transform(
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/nvtabular/nvtabular/ops/lambdaop.py", line 72, in transform
    new_df[col] = self.f(df[col], df)
  File "/tmp/ipykernel_11729/1746810471.py", line 3, in relative_price_to_avg_categ
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 723, in __getitem__
    return self._get_columns_by_label(arg, downcast=True)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py", line 1449, in _get_columns_by_label
    new_data = super()._get_columns_by_label(labels, downcast)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/frame.py", line 630, in _get_columns_by_label
    return self._data.select_by_label(labels)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py", line 346, in select_by_label
    return self._select_by_label_grouped(key)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py", line 408, in _select_by_label_grouped
    result = self._grouped_data[key]
KeyError: 'price'
0827 19:47:37.694518 420 pb_stub.cc:555] KeyError: 'price'

At:
  /usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py(408): _select_by_label_grouped
  /usr/local/lib/python3.8/dist-packages/cudf/core/column_accessor.py(346): select_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/frame.py(630): _get_columns_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(1449): _get_columns_by_label
  /usr/local/lib/python3.8/dist-packages/cudf/core/dataframe.py(723): __getitem__
  /usr/lib/python3.8/contextlib.py(75): inner
  /tmp/ipykernel_11729/1746810471.py(3): relative_price_to_avg_categ
  /nvtabular/nvtabular/ops/lambdaop.py(72): transform
  /usr/lib/python3.8/contextlib.py(75): inner
  /root/models/model_nvt/1/model.py(300): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(265): _transform_tensors
  /root/models/model_nvt/1/model.py(143): execute
```

Even though I remove both, it does not work.

**Comment by rnyak** [comment]
@jperez999 you can use this code to generate data and run NVT workflow and then generate config files.

```
NUM_ROWS = 10000
session_length = 20
inputs = {
    'session_id': numpy.random.randint(70000, 80000, NUM_ROWS),
    'day': numpy.random.randint(1, 10, NUM_ROWS),
    'item_id': numpy.random.randint(1, 51996, NUM_ROWS),
    'category': numpy.random.randint(1, 332, NUM_ROWS),
    'timestamp/age_days': numpy.random.uniform(0, 1, NUM_ROWS),
    'timestamp/weekday/sin' : numpy.random.uniform(0, 1, NUM_ROWS),
    'purchase': numpy.random.randint(0, 2, NUM_ROWS)
    }
random_data = cudf.DataFrame(inputs)


categ_feats = ['session_id', 'day', 'item_id', 'category'] >> nvt.ops.Categorify()
groupby_features = categ_feats + ['timestamp/age_days', 'timestamp/weekday/sin', 'purchase'] >> nvt.ops.Groupby(
    groupby_cols=["session_id"], 
    aggs={
        "item_id": ["list"],
        "category": ["list"],     
        "day": ["first"],
        "purchase": ["first"],
        "timestamp/age_days": ["list"],
        'timestamp/weekday/sin': ["list"],
        },
    name_sep="-")
# Trim sessions to first 20 items 
groupby_features_list = [x for x in groupby_features.output_columns.names if '-list' in x]

#groupby_features_nonlist:  need to fix a BUG related to adding two workflow nodes
groupby_features_trim = groupby_features[groupby_features_list] >> nvt.ops.ListSlice(0,20) >> nvt.ops.Rename(postfix = '_trim')
workflow = nvt.Workflow(groupby_features['day-first'] + groupby_features_trim)
dataset = nvt.Dataset(random_data, cpu=False)
workflow.fit(dataset)
sessions_gdf = workflow.transform(dataset).to_ddf().compute()


from nvtabular.inference.triton import generate_nvtabular_model
generate_nvtabular_model(
    workflow=workflow,
    name='model_nvt',
    output_path='/workspace/TF4Rec/models/model_nvt/',
)
```

Then you can run this code to send request to TRITON:

```
import os


import cudf
import tritonclient.grpc as grpcclient
import nvtabular.inference.triton as nvt_triton

import tritonhttpclient

try:
    triton_client = tritonhttpclient.InferenceServerClient(url="localhost:8000", verbose=True)
    print("client created.")
except Exception as e:
    print("channel creation failed: " + str(e))
    
    
triton_client.is_server_live()
batch = cudf.read_parquet('random_data.parquet', num_rows=3)[['session_id', 'day', 'item_id', 'category', 'timestamp/age_days',
       'timestamp/weekday/sin', 'purchase']]

inputs = nvt_triton.convert_df_to_triton_input(batch.columns, batch, grpcclient.InferInput)

output_names_org = ['day-first',
 'category-list_trim',
 'timestamp/weekday/sin-list_trim',
 'item_id-list_trim',
 'timestamp/age_days-list_trim']

output_names = []

for name in output_names_org:
    if '-list' in name:
        output_names.append(name + '__values')
        output_names.append(name + '__nnzs')
    else:
        output_names.append(name)
    

outputs = []

for col in output_names:
    outputs.append(grpcclient.InferRequestedOutput(col))
    
MODEL_NAME_NVT = "model_nvt"

with grpcclient.InferenceServerClient("localhost:8001") as client:
    response = client.infer(MODEL_NAME_NVT, inputs, request_id="1", outputs=outputs)

for col in output_names:
    print(col, response.as_numpy(col), response.as_numpy(col).shape)
```

**Comment by rnyak** [comment]
@jperez999 Please try the code in the gists.  The code generates its own random data.

**Comment by benfred** [comment]
@jperez999 is this fixed with https://github.com/NVIDIA/NVTabular/pull/1106 ?
