### ISSUE TITLE
[BUG] UCX issue for Multi-GPU criteo/DLRM 

### ISSUE THREAD

**Issue by PerkzZheng** [NVIDIA/NVTabular#358]
**Describe the bug**
UCX issue when trying to reproduce Multi-GPU criteo/DLRM script in NVTabular with some new Ops.
What the problem could be that lead to this error ?

**Steps/Code to reproduce bug**

when setting -p "ucx"

```
 device_size = device_mem_size(kind="total")

    if args.protocol == "ucx":
        UCX_TLS = os.environ.get("UCX_TLS", "tcp,cuda_copy,cuda_ipc,sockcm")
        os.environ["UCX_TLS"] = UCX_TLS
        cluster = LocalCUDACluster(
            protocol = args.protocol,
            CUDA_VISIBLE_DEVICES = args.devices,
            enable_nvlink=True,
            device_memory_limit = int(device_size * args.device_limit_frac),
            dashboard_address=":" + args.dashboard_port
        )
    else:
        cluster = LocalCUDACluster(
            protocol = args.protocol,
            CUDA_VISIBLE_DEVICES = args.devices,
            device_memory_limit = int(device_size * args.device_limit_frac),
            dashboard_address=":" + args.dashboard_port
        )
```
**Environment details (please complete the following information):**
 - Environment location: Docker NVTabular 0.2
 - Method of NVTabular install: `docker pull nvcr.io/nvidia/nvtabular:0.2`
 

**stderr output**
```

[1602819611.375410] [b4803745b8de:108  :0]           sock.c:344  UCX  ERROR send(fd=-1) failed: Bad file descriptor 
[1602819611.375642] [b4803745b8de:108  :0]           sock.c:344  UCX  ERROR send(fd=-1) failed: Bad file descriptor
[1602819612.383832] [b4803745b8de:108  :0]           sock.c:344  UCX  ERROR send(fd=-1) failed: Bad file descriptor 
[1602819612.383982] [b4803745b8de:108  :0]           sock.c:344  UCX  ERROR send(fd=-1) failed: Bad file descriptor
tornado.application - ERROR - Multiple exceptions in yield list 
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/ucx.py", line 299, in close
    await self.ep.send(struct.pack("?Q", True, 0))
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/endpoint_reuse.py", line 102, in send
    await self.handle.ep.send(buffer, nbytes=nbytes, tag=self.tag)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/core.py", line 583, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/comm.py", line 44, in tag_send
    event_loop, ucx_api.tag_send_nb, ep, buffer, nbytes, tag, name=name
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/comm.py", line 28, in _call_ucx_api
    req = func(*args, **kwargs)
  File "ucp/_libs/ucx_api.pyx", line 738, in ucp._libs.ucx_api.tag_send_nb
  File "ucp/_libs/ucx_api.pyx", line 620, in ucp._libs.ucx_api._handle_status
ucp.exceptions.UCXError: <[Send #4458] ep: 0x7f0d4c9490d8, tag: 0x1cb1d2508d33870b, nbytes: 16, type: <class 'bytes'>>: Input/output error
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/deploy/spec.py", line 641, in close_clusters
    cluster.close(timeout=10)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 92, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 171, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/deploy/spec.py", line 411, in _close
    await self.scheduler.close()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/scheduler.py", line 1583, in close
    await super(Scheduler, self).close() 
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 631, in close
    yield [comm.close() for comm in list(self._comms)]  # then forcefully close
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/ucx.py", line 299, in close
    await self.ep.send(struct.pack("?Q", True, 0))
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/endpoint_reuse.py", line 102, in send
    await self.handle.ep.send(buffer, nbytes=nbytes, tag=self.tag)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/core.py", line 583, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/comm.py", line 44, in tag_send
    event_loop, ucx_api.tag_send_nb, ep, buffer, nbytes, tag, name=name
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/ucp/comm.py", line 28, in _call_ucx_api
    req = func(*args, **kwargs)
  File "ucp/_libs/ucx_api.pyx", line 738, in ucp._libs.ucx_api.tag_send_nb
  File "ucp/_libs/ucx_api.pyx", line 620, in ucp._libs.ucx_api._handle_status
ucp.exceptions.UCXError: <[Send #4559] ep: 0x7f0d4c949120, tag: 0xaa09bc95b1afe2ed, nbytes: 16, type: <class 'bytes'>>: Input/output error
[1602819612.394868] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a297fc1c0 was not returned to mpool ucp_am_bufs
[1602819612.394884] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a2affc340 was not returned to mpool ucp_am_bufs
[1602819612.394888] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a2c7fc4c0 was not returned to mpool ucp_am_bufs
[1602819612.394891] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a2e7fc6c0 was not returned to mpool ucp_am_bufs
[1602819612.394894] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a2effc740 was not returned to mpool ucp_am_bufs
[1602819612.394898] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0a30ffc940 was not returned to mpool ucp_am_bufs
[1602819612.395106] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0adbffcc40 was not returned to mpool ucp_am_bufs
[1602819612.395138] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0adcffcd40 was not returned to mpool ucp_am_bufs
[1602819612.395166] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0addffce40 was not returned to mpool ucp_am_bufs
[1602819612.395179] [b4803745b8de:108  :1]          mpool.c:43   UCX  WARN  object 0x7f0adf7fcfc0 was not returned to mpool ucp_am_bufs
distributed.core - WARNING - rpc object <rpc to 'ucx://127.0.0.1:37263', 2 comms> deleted with 1 open comms
```

**Comment by PerkzZheng** [comment]
I have tried the original DLRM criteo mutli-gpu scrip in /examples, it is still leading to UCX errors when setting -p "ucx".

**Comment by viswa-nvidia** [comment]
@benfred should we be tracking this still ?
