### ISSUE TITLE
[BUG] Can't create a nvtabular Dataset with parquet files containing lists columns

### ISSUE THREAD

**Issue by abditag2** [NVIDIA/NVTabular#363]
After installing nvtabular version 0.2, I am getting this error when running `dataloader_bench.py` example: 

Command to run the example:
```
python dataloader_bench.py torch <PATH TO Folder with Parquet Files on local> parquet 0.2
```
Error:
```
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main(args)
  File "main.py", line 61, in main
    train_paths, engine="parquet", part_mem_fraction=float(args.gpu_mem_frac)
  File "/root/miniconda/lib/python3.7/site-packages/nvtabular/io/dataset.py", line 224, in __init__
    paths, part_size, storage_options=storage_options, **kwargs
  File "/root/miniconda/lib/python3.7/site-packages/nvtabular/io/parquet.py", line 69, in __init__
    .memory_usage(deep=True, index=True)
  File "/root/miniconda/lib/python3.7/site-packages/cudf/core/dataframe.py", line 842, in memory_usage
    sizes = [col._memory_usage(deep=deep) for col in self._data.columns]
  File "/root/miniconda/lib/python3.7/site-packages/cudf/core/dataframe.py", line 842, in <listcomp>
    sizes = [col._memory_usage(deep=deep) for col in self._data.columns]
  File "/root/miniconda/lib/python3.7/site-packages/cudf/core/column/column.py", line 299, in _memory_usage
    return self.__sizeof__()
  File "/root/miniconda/lib/python3.7/site-packages/cudf/core/column/column.py", line 183, in __sizeof__
    n = self.data.size
  File "cudf/_lib/column.pyx", line 99, in cudf._lib.column.Column.data.__get__
AttributeError: 'ListDtype' object has no attribute 'itemsize'
```

My conda env:
```
# packages in environment at /root/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_pytorch_select           0.1                       cpu_0
abseil-cpp                20200225.2           he1b5a44_2    conda-forge
arrow-cpp                 0.17.1          py37h1234567_11_cuda    conda-forge
arrow-cpp-proc            1.0.1                      cuda    conda-forge
aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
blas                      1.0                         mkl
bokeh                     2.2.2                    py37_0
boost-cpp                 1.72.0               h9359b55_3    conda-forge
brotli                    1.0.9                he6710b0_2
brotlipy                  0.7.0           py37h7b6447c_1000
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.16.1               h7b6447c_0
ca-certificates           2020.10.14                    0
certifi                   2020.6.20                py37_0
cffi                      1.14.3           py37he30daa8_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
cloudpickle               1.6.0                      py_0
conda                     4.9.0            py37he5f6b98_0    conda-forge
conda-package-handling    1.7.2            py37h03888b9_0
cryptography              3.1.1            py37h1ba5d50_0
cudatoolkit               10.2.89              h6bb024c_0    nvidia
cudf                      0.15.0          cuda_10.2_py37_g71cb8c0e0_0    rapidsai
cudnn                     7.6.5                cuda10.2_0
cupy                      7.8.0            py37h940342b_1    conda-forge
curl                      7.71.1               hbc83047_1
cython                    0.29.21                  pypi_0    pypi
cytoolz                   0.11.0           py37h7b6447c_0
dask                      2.30.0                     py_0
dask-core                 2.30.0                     py_0
dask-cudf                 0.15.0          py37_g71cb8c0e0_0    rapidsai
distributed               2.30.0                   py37_0
dlpack                    0.3                  he6710b0_1
double-conversion         3.1.5                he6710b0_1
fastavro                  1.0.0.post1      py37h7b6447c_0
fastrlock                 0.5              py37he6710b0_0
freetype                  2.10.3               h5ab3b9f_0
fsspec                    0.8.3                      py_0
gflags                    2.2.2                he6710b0_0
glog                      0.4.0                he6710b0_0
grpc-cpp                  1.30.2               heedbac9_0    conda-forge
heapdict                  1.0.1                      py_0
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10                       py_0
intel-openmp              2019.4                      243
jinja2                    2.11.2                     py_0
jpeg                      9b                   h024ee3a_2
krb5                      1.18.2               h173b8e3_0
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libcudf                   0.15.0          cuda10.2_g71cb8c0e0_0    rapidsai
libcurl                   7.71.1               h20c2e04_1
libedit                   3.1.20191231         h14c3975_1
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libllvm10                 10.0.1               hbcb73fb_5
libpng                    1.6.37               hbc83047_0
libprotobuf               3.12.4               hd408876_0
librmm                    0.15.0          cuda10.2_g8005ca5_0    rapidsai
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
libthrift                 0.13.0               hbe8ec66_6    conda-forge
libtiff                   4.1.0                h2733197_1
llvmlite                  0.34.0           py37h269e1b5_4
locket                    0.2.0                    py37_1
lz4-c                     1.9.2                heb0550a_3
markupsafe                1.1.1            py37h14c3975_1
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.2.0            py37h23d657b_0
mkl_random                1.1.0            py37hd6b4f25_0
msgpack-python            1.0.0            py37hfd86e86_1
nccl                      2.7.8.1              hc6a2c23_1    conda-forge
ncurses                   6.2                  he6710b0_1
ninja                     1.10.1           py37hfd86e86_0
numba                     0.51.2           py37h04863e7_1
numpy                     1.19.1           py37hbc911f0_0
numpy-base                1.19.1           py37hfa32c7d_0
nvtabular                 0.2.0           cudaunknown_py37_0    nvidia/label/nvidia
olefile                   0.46                     py37_0
openssl                   1.1.1h               h7b6447c_0
packaging                 20.4                       py_0
pandas                    1.1.3            py37he6710b0_0
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.1.0                      py_0
pillow                    8.0.0            py37h9a89aac_0
pip                       20.2.3                   py37_0
psutil                    5.7.2            py37h7b6447c_0
pyarrow                   0.17.1          py37h1234567_11_cuda    conda-forge
pycosat                   0.6.3            py37h7b6447c_0
pycparser                 2.19                     pypi_0    pypi
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pysocks                   1.7.1                    py37_1
python                    3.7.9                h7579374_0
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.0           cpu_py37hd91cbb3_0
pytz                      2020.1                     py_0
pyyaml                    5.3.1            py37h7b6447c_1
re2                       2020.07.06           he1b5a44_1    conda-forge
readline                  8.0                  h7b6447c_0
requests                  2.24.0                     py_0
rmm                       0.15.0          cuda_10.2_py37_g8005ca5_0    rapidsai
ruamel_yaml               0.15.87          py37h7b6447c_1
setuptools                50.3.0           py37hb0f4dca_1
six                       1.15.0                     py_0
snappy                    1.1.8                he6710b0_0
sortedcontainers          2.2.2                      py_0
spdlog                    1.8.0                hfd86e86_1
sqlite                    3.33.0               h62c20be_0
tbb                       2020.3               hfd86e86_0
tblib                     1.7.0                      py_0
thrift-compiler           0.13.0               hbe8ec66_6    conda-forge
thrift-cpp                0.13.0                        6    conda-forge
tk                        8.6.10               hbc83047_0
toolz                     0.11.1                     py_0
tornado                   6.0.4            py37h7b6447c_1
tqdm                      4.50.2                     py_0
typing_extensions         3.7.4.3                    py_0
urllib3                   1.25.10                    py_0
wheel                     0.35.1                     py_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zict                      2.0.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0
```

**Comment by benfred** [comment]
Hi Fardin, thanks for trying out NVTabular!

It looks like your parquet dataset contains some list columns - and you're hitting a bug with calculating the memory usage for these list columns.

We're adding support for list columns in the next release of NVTabular (0.3), including the ability to use list columns for multi-hot categorical encoding and using those multihot columns in our dataloaders. We will have a workaround for this bug in the NVT 0.3 release, and I have also submitted a fix to cudf (https://github.com/rapidsai/cudf/pull/6549) to fix upstream.

In the meantime you will need to either specify the number of rowgroups you want to process per partition to avoid the memory_usage call (```dataset = nvtabular.Dataset(dataset_path, row_groups_per_part=10)```) or run on a dataset without list columns.

**Comment by abditag2** [comment]
Thanks guys!
