### ISSUE TITLE
[BUG] Intermitent OOM issues with a NVT workflow

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA/NVTabular#442]
**Describe the bug**
I am working in an internal NVIDIA project using a large dataset. I am getting many intermitent OOM and timeout issues with an NVTabular workflow (0.3 version). From the error message, it seems to be related to Dask distributed.

**Steps/Code to reproduce bug**
- In this [Google Drive](https://drive.google.com/drive/u/1/folders/1mOfgWTSG9fMWN99bJry_GywL2RXuRE_V) (internal for NVIDIA), there is a notebook to reproduce the error and also logs of three NGC jobs which failed due to that error (see the error in a selected part of the log files in the end of this issue description).

- In order to reproduce the error, and get access to the necessary data, check the "NGC batch command.txt" in the shared Google Drive

The error happens in the following cell of the notebook.

```python
%%time
shuffle = None  # Shuffle.PER_PARTITION  #Shuffle.PER_WORKER  # Per-worker option currently requires the entire output dataset to fit in host memory. 
out_files_per_proc = 10        # Number of outp t files per worker
workflow.apply(
    ds,
    output_format="parquet", #"parquet"
    output_path=os.path.join(demo_output_path,"processed_train"),
    shuffle=shuffle,
    out_files_per_proc=out_files_per_proc,
)
```

```
**Selected section of the NGC instance log (error_memory_nvt_1604019.log)**

* hwloc 1.11.9 has encountered what looks like an error from the operating system.
*
* L3 (cpuset 0x000000ff,0xffffff00,0xffffffff) intersects with NUMANode (P#1 cpuset 0x0000ffff,0xf00000ff,0xfff00000 nodeset 0x00000002) without inclusion!
* Error occurred in topology.c line 1088
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with the files generated by the hwloc-gather-topology script.
****************************************************************************
[I 13:27:24.773 NotebookApp] Saving file at /gfn-merlin/gmoreira/preprocess/nvtabular-prep-32-features-gmoreira-53-dataset-with-more-features-8x32GB_GPU-NVT0.3.ipynb
[W 13:27:24.775 NotebookApp] Notebook gfn-merlin/gmoreira/preprocess/nvtabular-prep-32-features-gmoreira-53-dataset-with-more-features-8x32GB_GPU-NVT0.3.ipynb is not trusted
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(27): warning: thrust/optional.h: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/types.hpp(29): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
[W 13:39:19.653 NotebookApp] WebSocket ping timeout after 119674 ms.
[I 13:39:24.657 NotebookApp] Starting buffering for 8b05ddd0-51d1-477b-a26f-4b0470bd4d31:453b78dc1acc44ce89daf9cee5cc8b0e
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:41173
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:41173 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:44663
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:44663 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:38293
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:38293 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:41173
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:41173 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:38293
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:38293 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:44663
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:44663 after 10 s
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:38293
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3255, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/worker.py", line 3232, in _get_data
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 1035, in connect
    **self.connection_args,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:38293 after 10 s
distributed.worker - WARNING - Heartbeat to scheduler failed
/opt/conda/envs/rapids/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 48 leaked semaphores to clean up at shutdown
  len(cache))
[I 17:25:48.901 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[C 17:25:53.762 NotebookApp] received signal 15, stopping
[I 17:25:53.763 NotebookApp] Shutting down 1 kernel
[I 17:25:53.964 NotebookApp] Kernel shutdown: 8b05ddd0-51d1-477b-a26f-4b0470bd4d31
[I 17:25:53.965 NotebookApp] Shutting down 0 terminals
```

**Comment by viswa-nvidia** [comment]
pushing this to needs triage to see if this bug should still be fixed

**Comment by viswa-nvidia** [comment]
Retiring this bug.
