### ISSUE TITLE
[Task] CI is failing on importing fast.ai

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#493]
Our CI system is failing to run our notebooks,  failing on importing fast.ai:

```
/opt/conda/envs/rapids/lib/python3.7/subprocess.py:512: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/tmp/pytest-of-jenkins/pytest-2/test_criteo_notebook0/notebook.py", line 30, in <module>
    from fastai.basics import Learner
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fastai/basics.py", line 1, in <module>
    from .data.all import *
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fastai/data/all.py", line 2, in <module>
    from .core import *
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fastai/data/core.py", line 379, in <module>
    def test_dl(self:DataLoaders, test_items, rm_type_tfms=None, with_labels=False, **kwargs):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fastcore/meta.py", line 116, in _f
    sig = inspect.signature(from_f)
  File "/opt/conda/envs/rapids/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/opt/conda/envs/rapids/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/opt/conda/envs/rapids/lib/python3.7/inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object
```

**Comment by benfred** [comment]
This has been fixed by upgrading the CI container to a newer version of fast.ai
