### ISSUE TITLE
[BUG] Cannot write in GS

### ISSUE THREAD

**Issue by albert17** [NVIDIA/NVTabular#555]
In Google Cloud Storage, I am able to read data from the bucket but I cannot write data. 

At the beginning I loging: `gcloud auth login --no-launch-browser` 

This is the testing program using `gcsfs` (btw, DEBUG is not showing anything)
```
import gcsfs
import os

DEBUG = os.environ.get('GCSFS_DEBUG', True)

fs = gcsfs.GCSFileSystem()
f = fs.open("merlin-datasets/test.txt", 'wb')
f.write(2*2**20 * b'a')
f.close()
```

I get an `Insufficient Permission` error
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    f.close()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1483, in close
    self.flush(force=True)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1354, in flush
    self._initiate_upload()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1409, in _initiate_upload
    self.metadata,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1492, in initiate_upload
    headers={"X-Upload-Content-Type": content_type},
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    self.validate_response(status, contents, json, path, headers)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1222, in validate_response
    raise IOError("Forbidden: %s\n%s" % (path, msg))
OSError: Forbidden: https://www.googleapis.com/upload/storage/v1/b/merlin-datasets/o
Insufficient Permission
```

I should have both reading and writing permissions, as I can see in the IAM policy.
```
(rapids) root@b737df9c8ee2:/# gsutil iam get gs://merlin-datasets
{
  "bindings": [
    {
      "members": [
        "projectEditor:merlin-295819",
        "projectOwner:merlin-295819",
        "user:albertoa@nvidia.com"
      ],
      "role": "roles/storage.legacyBucketOwner"
    },
    {
      "members": [
        "projectViewer:merlin-295819"
      ],
      "role": "roles/storage.legacyBucketReader"
    },
    {
      "members": [
        "projectEditor:merlin-295819"
      ],
      "role": "roles/storage.legacyBucketWriter"
    },
    {
      "members": [
        "projectOwner:merlin-295819"
      ],
      "role": "roles/storage.legacyObjectOwner"
    },
    {
      "members": [
        "projectViewer:merlin-295819"
      ],
      "role": "roles/storage.legacyObjectReader"
    }
  ],
  "etag": "CAM="
}
```

What I find suprising is that I can actually upload a file to the bucket using `gsutil `
```
(rapids) root@b737df9c8ee2:/# gsutil cp test.py gs://merlin-datasets
Copying file://test.py [Content-Type=text/x-python]...
/ [1 files][  190.0 B/  190.0 B]                                                
Operation completed over 1 objects/190.0 B.   
```

Any idea about what it could be going on @quasiben @martindurant ?

**Comment by quasiben** [comment]
@albert17 I would suggest moving this to the gcsfs repo if you think there is a bug.  Looking briefly, it looks like you need to include the project name in the `GCSFileSystem` call

> gcsfs.GCSFileSystem(project='my-google-project')

**Comment by albert17** [comment]
I am not sure if there is bug, or I am not configuring properly GCP.

`GCSFileSystem ` seems to work without setting the project (it gets the one I am logged in), I am able to list the bucket.

```
fs = gcsfs.GCSFileSystem()
print(fs.ls('merlin-datasets'))
```
```
['merlin-datasets/crit_int_pq', 'merlin-datasets/test.py']
```

**Comment by quasiben** [comment]
@ayushdg have you experienced any issues with writing to gcsfs?

**Comment by albert17** [comment]
It works. The problem is that the VM was not configures properly. It requires:
```
Cloud API access scopes
Allow full access to all Cloud APIs
```
