### ISSUE TITLE
[BUG] Getting Error from winning-solution-recsys2020-twitter notebook

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#665]
**Describe the bug**
This GH issue is related to the winning-solution-recsys2020-twitter/01-02-04-Download-Convert-ETL-with-NVTabular-Training-with-XGBoost.ipynb notebook. I am getting the following error from this cell:

```
%%time

time_preproc_start = time.time()
proc.fit(trains_itrs)
time_preproc = time.time()-time_preproc_start
```
```
Failed to transform operator <nvtabular.ops.lambdaop.LambdaOp object at 0x7f0ff14d3040>
Traceback (most recent call last):
  File "/nvtabular/nvtabular/workflow.py", line 331, in _transform_partition
    df = column_group.op.transform(column_group.input_column_names, df)
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/nvtabular/nvtabular/ops/lambdaop.py", line 75, in transform
    new_df[col] = self.f(df[col])
  File "<ipython-input-15-ff1c69a2bb08>", line 1, in <lambda>
    split_media = nvt.ColumnGroup(['media']) >> (lambda col: splitmedia(col))
  File "<ipython-input-13-d2f4cd9a1339>", line 5, in splitmedia
    return(col.str.split('\t')[0].fillna('') + '_' + col.str.split('\t')[1].fillna(''))
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py", line 874, in __getitem__
    return self.loc[arg]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexing.py", line 140, in __getitem__
    return self._sr.iloc[arg]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexing.py", line 79, in __getitem__
    data = self._sr._column[arg]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 627, in __getitem__
    return self.element_indexing(int(arg))
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 605, in element_indexing
    return libcudf.copying.get_element(self, idx).value
  File "cudf/_lib/copying.pyx", line 675, in cudf._lib.copying.get_element
RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1614191054479/work/cpp/src/copying/get_element.cu:125: get_element_functor not supported for list_view
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

/nvtabular/nvtabular/workflow.py in fit(self, dataset)
    137                 results = [r.result() for r in self.client.compute(stats)]
    138             else:
--> 139                 results = dask.compute(stats, scheduler="synchronous")[0]
    140 
    141             for computed_stats, op in zip(results, ops):

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    563         postcomputes.append(x.__dask_postcompute__())
    564 
--> 565     results = schedule(dsk, keys, **kwargs)
    566     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    567 

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    526     """
    527     kwargs.pop("num_workers", None)  # if num_workers present, remove it
--> 528     return get_async(apply_sync, 1, dsk, keys, **kwargs)
    529 
    530 

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    493 
    494                 while state["ready"] and len(state["running"]) < num_workers:
--> 495                     fire_task()
    496 
    497             succeeded = True

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in fire_task()
    455                 )
    456                 # Submit
--> 457                 apply_async(
    458                     execute_task,
    459                     args=(

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in apply_sync(func, args, kwds, callback)
    515 def apply_sync(func, args=(), kwds={}, callback=None):
    516     """ A naive synchronous version of apply_async """
--> 517     res = func(*args, **kwds)
    518     if callback is not None:
    519         callback(res)

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    225         failed = False
    226     except BaseException as e:
--> 227         result = pack_exception(e, dumps)
    228         failed = True
    229     return key, result, failed

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/optimization.py in __call__(self, *args)
    961         if not len(args) == len(self.inkeys):
    962             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 963         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    964 
    965     def __reduce__(self):

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/core.py in get(dsk, out, cache)
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/utils.py in apply(func, args, kwargs)
     33 def apply(func, args, kwargs=None):
     34     if kwargs:
---> 35         return func(*args, **kwargs)
     36     else:
     37         return func(*args)

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)
   5485     func = kwargs.pop("_func")
   5486     meta = kwargs.pop("_meta")
-> 5487     df = func(*args, **kwargs)
   5488     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   5489         if not len(df):

/nvtabular/nvtabular/workflow.py in _transform_partition(root_df, column_groups)
    314             for parent in column_group.parents:
    315                 unique_flattened_cols_parent = _get_unique(parent.flattened_columns)
--> 316                 parent_df = _transform_partition(root_df, [parent])
    317                 if df is None or not len(df):
    318                     df = parent_df[unique_flattened_cols_parent]

/nvtabular/nvtabular/workflow.py in _transform_partition(root_df, column_groups)
    329         if column_group.op:
    330             try:
--> 331                 df = column_group.op.transform(column_group.input_column_names, df)
    332             except Exception:
    333                 LOG.exception("Failed to transform operator %s", column_group.op)

/opt/conda/envs/rapids/lib/python3.8/contextlib.py in inner(*args, **kwds)
     73         def inner(*args, **kwds):
     74             with self._recreate_cm():
---> 75                 return func(*args, **kwds)
     76         return inner
     77 

/nvtabular/nvtabular/ops/lambdaop.py in transform(self, columns, df)
     73                 new_df[col] = self.f(df[col], df)
     74             elif self._param_count == 1:
---> 75                 new_df[col] = self.f(df[col])
     76             else:
     77                 # shouldn't ever happen,

<ipython-input-15-ff1c69a2bb08> in <lambda>(col)
----> 1 split_media = nvt.ColumnGroup(['media']) >> (lambda col: splitmedia(col))

<ipython-input-13-d2f4cd9a1339> in splitmedia(col)
      3         return(col)
      4     else:
----> 5         return(col.str.split('\t')[0].fillna('') + '_' + col.str.split('\t')[1].fillna(''))
      6 
      7 def count_token(col,token):

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in __getitem__(self, arg)
    872             return self.iloc[arg]
    873         else:
--> 874             return self.loc[arg]
    875 
    876     def __iter__(self):

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexing.py in __getitem__(self, arg)
    138             raise KeyError(arg)
    139 
--> 140         return self._sr.iloc[arg]
    141 
    142     def __setitem__(self, key, value):

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexing.py in __getitem__(self, arg)
     77         if isinstance(arg, tuple):
     78             arg = list(arg)
---> 79         data = self._sr._column[arg]
     80 
     81         if is_scalar(data) or _is_null_host_scalar(data):

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py in __getitem__(self, arg)
    625     def __getitem__(self, arg) -> Union[ScalarLike, ColumnBase]:
    626         if is_scalar(arg):
--> 627             return self.element_indexing(int(arg))
    628         elif isinstance(arg, slice):
    629             start, stop, stride = arg.indices(len(self))

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py in element_indexing(self, index)
    603             raise IndexError("single positional indexer is out-of-bounds")
    604 
--> 605         return libcudf.copying.get_element(self, idx).value
    606 
    607     def slice(self, start: int, stop: int, stride: int = None) -> ColumnBase:

cudf/_lib/copying.pyx in cudf._lib.copying.get_element()

RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1614191054479/work/cpp/src/copying/get_element.cu:125: get_element_functor not supported for list_view
```

The issue is related to Lambda op, but also, I think `['hashtags', 'domains', 'links']` columns should be properly split at first. There is `splitmedia` function which is applied only on `media` column.  It can be used to split these multi-hot columns too. Without proper split, `Cateforify` op would not create encoded multi-hot columns for these `['hashtags', 'domains', 'links']` columns, if that's the idea here.

**Steps/Code to reproduce bug**
Run the notebook using the `training.tsv` file.

**Expected behavior**
Notebook should work E2E without errors.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]:  Docker : `nvidia/merlin/merlin-training:0.4` image. 
 - Method of NVTabular install: using NGC and docker image.
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Comment by benfred** [comment]
Fixed by https://github.com/NVIDIA/NVTabular/pull/692
