### ISSUE TITLE
[QST] KerasSequenceLoader with parquet format reports OOM

### ISSUE THREAD

**Issue by JinrongGuo1** [NVIDIA/NVTabular#967]
I try to run the example in "examples/tensorflow/accelerating-tensorflow.ipynb" with criteo day_1 dataset parquet format, and met the error of OOM "**MemoryError: std::bad_alloc: CUDA error at: /usr/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory**". 

After some checks, I found the error lies in the operation of "online_workflow.transform(dataset)" in "KerasSequenceLoader" API, the "online_workflow" returned by "make_feature_column_workflow(*)" doesn't support cluster mode, so, on single GPU, OOM raises.

ps. my GPU is P40 with 24GB memory.

How to resolve this error? Besides, I wonder whether the "online_workflow.transform(dataset)" load the whole dataset into memory and transform it, rather than a minibatch?

**Comment by bschifferer** [comment]
@JinrongGuo1 

Thanks for the feedback. Is it correct, that you run into the error, when you execute following cell:
```
history = model.fit(train_dataset_tf, callbacks=[validation_callback], epochs=1)
```

The notebook was created with a GPU with 32GB memory. Have you tried to adjust the memory limits for TensorFlow
```
os.environ["TF_MEMORY_ALLOCATION"] = "0.5"  # fraction of free memory
```
In addition or as an alternative, you can reduce the batch_size of the data loader.

TensorFlow will reserve all free GPU memory. TF_MEMORY_ALLOCATION limits TensorFlow to reserve all GPU memory. As KerasSequenceLoader is a GPU dataloader, we need to provide some GPU memory to the dataloader.

The online.workflow is a functionality used for online transform, for example used by TensorFlow feature columns. NVTabular supports to execute some of the TensorFlow feature column on the GPU. For example, when we create cross columns or hash categorical columns. It should transform per batch.

**Comment by JinrongGuo1** [comment]
@bschifferer Thanks for your feedback.

It's true the error raises in "model.fit()" cell. I've tried again to set BATCH_SIZE  as 1, and adjust "TF_MEMORY_ALLOCATION" from 0.1-0.9, still the same error. Detail as below

`Traceback (most recent call last):
  File "v1/nvt_parquet_dataloader_main.py", line 387, in <module>
    fit_a_model(accelerated=True, cpu=False)
  File "v1/nvt_parquet_dataloader_main.py", line 333, in fit_a_model
    train_dataset, columns = make_dataset(file_pattern, columns, accelerated=accelerated)
  File "v1/nvt_parquet_dataloader_main.py", line 174, in make_dataset
    ds = KerasSequenceLoader(
  File "/nvtabular/nvtabular/loader/tensorflow.py", line 225, in __init__
    DataLoader.__init__(
  File "/nvtabular/nvtabular/loader/backend.py", line 204, in __init__
    self._buff_len = len(self._buff)
  File "/nvtabular/nvtabular/loader/backend.py", line 64, in __len__
    return len(self.itr)
  File "/nvtabular/nvtabular/io/dataset.py", line 1019, in __len__
    return len(self._ddf)
  File "/usr/local/lib/python3.8/dist-packages/dask/dataframe/core.py", line 3805, in __len__
    return len(s)
  File "/usr/local/lib/python3.8/dist-packages/dask/dataframe/core.py", line 558, in __len__
    return self.reduction(
  File "/usr/local/lib/python3.8/dist-packages/dask/base.py", line 284, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dask/base.py", line 566, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/usr/local/lib/python3.8/dist-packages/dask/local.py", line 514, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.8/dist-packages/dask/local.py", line 325, in reraise
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 115, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 115, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.8/dist-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.8/dist-packages/dask/dataframe/io/parquet/core.py", line 381, in read_parquet_part
    dfs = [
  File "/usr/local/lib/python3.8/dist-packages/dask/dataframe/io/parquet/core.py", line 382, in <listcomp>
    func(fs, rg, columns.copy(), index, **toolz.merge(kwargs, kw))
  File "/usr/local/lib/python3.8/dist-packages/dask_cudf/io/parquet.py", line 61, in read_partition
    df = cudf.read_parquet(
  File "/usr/local/lib/python3.8/dist-packages/cudf/io/parquet.py", line 251, in read_parquet
    return libparquet.read_parquet(
  File "cudf/_lib/parquet.pyx", line 110, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 160, in cudf._lib.parquet.read_parquet
MemoryError: std::bad_alloc: CUDA error at: /usr/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory` 

It's a bit weird. If KerasSequenceLoader reads and transforms a single batch, rather than the whole dataset, even with the default BATCH_SIZE 65536 in the notebook, I think it's not that big exhausting 24GB GPU memory, original TF works well with 24GB. Even worse, in my case, BATCH_SIZE 1 doesn't get around this too.

**Comment by rnyak** [comment]
@JinrongGuo1 can you also try to reduce the `buffer_size`  in the `KerasSequenceLoader()` please?  If it is 0.06 try 0.02 both for train_dataset, and validation_dataset. You can then increase the batch_size and play with these parameters.

As an example:
```
        ds = KerasSequenceLoader(
            online_workflow.transform(dataset),
            batch_size=BATCH_SIZE,
            label_names=[LABEL_NAME],
            feature_columns=columns,
            shuffle=True,
            buffer_size=0.02,
            parts_per_chunk=1,
        )
```
